Update user guide for add and delete position
AY2122S1-CS2103-F10-1/tp pull request #16
Opened 2021-09-29 11:37 UTC by Harry-Gao-H

Update user guide for add and delete position and also modify the introduction of user guide

2021-09-29 14:05 UTC, BenjaminTan99 requested changes
Some minor errors but LGTM.

2021-09-29 14:05 UTC, BenjaminTan99 commented on docs/UserGuide.md
> +* `add postion pos/software engineer desc/work in a team that builds a face recognition application`
Typo for 'add postion' should be position

2021-09-29 14:05 UTC, BenjaminTan99 commented on docs/UserGuide.md
> +Format: `add position pos/POSITION desc/DESCRPTION`
Typo for DESCRPTION should be DESCRIPTION

2021-09-29 17:31 UTC, LMAOboxhack reviewed
Some discussions on command syntax & typo nits, otherwise LGTM!

2021-09-29 17:31 UTC, LMAOboxhack commented on docs/UserGuide.md
> +MrTechRecruiter (MTR) is a **desktop app for managing job application, optimized for use via a Command Line Interface** (CLI) while still having the benefits of a Graphical User Interface (GUI). If y
```suggestion
MrTechRecruiter (MTR) is a **desktop app for managing job applications, optimized for use via a Command Line Interface** (CLI) while still having the benefits of a Graphical User Interface (GUI). If you can type fast, MTR can get your application management tasks done faster than traditional GUI apps.
```

2021-09-29 17:31 UTC, LMAOboxhack commented on docs/UserGuide.md
> +* `add postion pos/software engineer desc/work in a team that builds a face recognition application`
```suggestion
* `add postion pos/software engineer desc/work in a team that builds a facial recognition application`
```

2021-09-29 17:31 UTC, LMAOboxhack commented on docs/UserGuide.md
> +* The name refers to the name of the positions as shown in the displayed position list.
```suggestion
Format: `delete position name/NAME`

* Deletes the position with the specified `NAME`.
* The name refers to the name of the position as displayed in the list of positions.
```

Might consider changing `pos/POSITION` to `name/NAME` instead for better clarity? (for `add` as well)
"Deletes the position with the specified `POSITION`" is a little ambiguous.

2021-09-30 11:22 UTC, Harry-Gao-H commented on docs/UserGuide.md
> +* The name refers to the name of the positions as shown in the displayed position list.
Yes `name` is clearer :slightly_smiling_face: Thanks for pointing that out.

2021-09-30 16:27 UTC, merged