Update developer guide for add&delete position.
AY2122S1-CS2103-F10-1/tp pull request #17
Opened 2021-09-29 12:19 UTC by Harry-Gao-H

Update developer guide for add&delete position. 
Add to NFR.

2021-09-29 14:19 UTC, BenjaminTan99 requested changes

2021-09-29 14:19 UTC, BenjaminTan99 commented on docs/DeveloperGuide.md
> +1. User requests to list positions
I think this listing itself can be another use case (e.g. Request list of positions) such that the line becomes something like
1. User requests and is shown all current list positions (UC3).
2. User requests to delete...

2021-09-29 14:19 UTC, BenjaminTan99 commented on docs/DeveloperGuide.md
> +  * 3a1. MrTechRecruiter shows an error message.
Similar comments as the earlier error message comment.

2021-09-29 14:19 UTC, BenjaminTan99 commented on docs/DeveloperGuide.md
> +    * 1a1. MrTechRecruiter shows an error message.
Similar to the earlier error message comments.

2021-09-29 14:20 UTC, BenjaminTan99 requested changes
Needs some adjustments for user stories.

2021-09-30 12:11 UTC, Harry-Gao-H commented on docs/DeveloperGuide.md
> +**Use case: Add a new position**
That's a good idea I think. Will add indices to **Use Case**

2021-09-30 12:17 UTC, Harry-Gao-H commented on docs/DeveloperGuide.md
> +* 1a. The format is invalid.
Use case detects the **interaction** between the user and the system, so I think 1a in your comment may be unnecessary. 
And `requests for the correct data` can be a part of `show an error message`?

2021-09-30 12:19 UTC, Harry-Gao-H commented on docs/DeveloperGuide.md
> +1. User requests to list positions
`list position` can be another use case that later we can refer to I think.

2021-09-30 12:24 UTC, Harry-Gao-H commented on docs/DeveloperGuide.md
> +* 2a. The list is empty.
Thanks for pointing that out :)

2021-10-01 04:06 UTC, BenjaminTan99 commented on docs/DeveloperGuide.md
> +**Use case: Add a new position**
ok i understand! no worries

2021-10-01 04:06 UTC, BenjaminTan99 commented on docs/DeveloperGuide.md
> +* 1a. The format is invalid.
Yes possible.

2021-10-01 04:07 UTC, BenjaminTan99 approved these changes

2021-10-01 04:11 UTC, merged