Add tests
AY2122S1-CS2103-F10-1/tp pull request #195
Opened 2021-11-04 13:02 UTC by Harry-Gao-H

2021-11-04 14:39 UTC, BenjaminTan99 requested changes
Generally LGTM, some changes required.

2021-11-04 14:39 UTC, BenjaminTan99 commented on src/main/java/seedu/address/model/applicant/ProfileUrl.java
> +    //better give an example of a valid url?
Think this is outdated from Darren's PR

2021-11-04 14:39 UTC, BenjaminTan99 commented on src/test/java/seedu/address/logic/commands/DeleteApplicantCommandTest.java
> +
I think all the command tests can have an equals() method

2021-11-04 14:39 UTC, BenjaminTan99 commented on src/test/java/seedu/address/logic/commands/EditApplicantCommandTest.java
> +
Missing equals() method

2021-11-04 14:39 UTC, BenjaminTan99 commented on src/test/java/seedu/address/testutil/EditApplicantDescriptorBuilder.java
> +        descriptor = new EditApplicantDescriptor();
```suggestion
        this.descriptor = new EditApplicantDescriptor();
```

2021-11-04 14:39 UTC, BenjaminTan99 commented on src/test/java/seedu/address/testutil/EditApplicantDescriptorBuilder.java
> +        return descriptor;
```suggestion
        return this.descriptor;
```

2021-11-04 15:03 UTC, Harry-Gao-H commented on src/main/java/seedu/address/model/applicant/ProfileUrl.java
> +    //better give an example of a valid url?
I don't think we need to test everything when there are so many missing tests

2021-11-04 15:03 UTC, Harry-Gao-H commented on src/test/java/seedu/address/logic/commands/DeleteApplicantCommandTest.java
> +
I don't think we need to test everything when there are so many missing tests

2021-11-04 15:04 UTC, Harry-Gao-H commented on src/main/java/seedu/address/model/applicant/ProfileUrl.java
> +    //better give an example of a valid url?
ok will merge

2021-11-05 10:11 UTC, BenjaminTan99 commented on src/test/java/seedu/address/logic/commands/DeleteApplicantCommandTest.java
> +
ok i understand

2021-11-05 10:12 UTC, BenjaminTan99 approved these changes

2021-11-05 10:12 UTC, BenjaminTan99 commented
Merge conflicts need to be resolved.

2021-11-06 03:53 UTC, LMAOboxhack approved these changes
LGTM

2021-11-06 03:53 UTC, LMAOboxhack commented on src/test/java/seedu/address/logic/commands/AddApplicantCommandIntegrationTest.java
> +        ApplicantParticulars validParticulars = new ApplicantBuilder().withPosition(validPosition).getParticulars();
Perhaps it might be better to abstract this out to abstract this out to a `ApplicantParticularsBuilder` class, but given that the `ApplicantParticulars` class is pretty simple & the v1.4 deadline is so close, I think we can skip it.

2021-11-06 04:02 UTC, Harry-Gao-H commented on src/test/java/seedu/address/logic/commands/AddApplicantCommandIntegrationTest.java
> +        ApplicantParticulars validParticulars = new ApplicantBuilder().withPosition(validPosition).getParticulars();
OKay

2021-11-06 04:25 UTC, merged