Update UG with find function, update various DG sections
AY2122S1-CS2103-F10-1/tp pull request #24
Opened 2021-09-29 16:26 UTC by LMAOboxhack

Added `find` function to Features section in User Guide.
Added target user profile, value proposition, non-functional requirements, user story & use cases for `find` function to Developer Guide.

2021-09-30 09:06 UTC, BenjaminTan99 requested changes
Some edits required before pushing.

2021-09-30 09:06 UTC, BenjaminTan99 commented on docs/DeveloperGuide.md
> +| `* * *`  | user                                       | easily search all relevant applicants through keywords         | I can compare applicants' relevant information |
```suggestion
| `* * *`  | user                                       | easily search all relevant applicants through keywords         | compare applicants' relevant information |
```
'I can' is already at the header of the table.

2021-09-30 09:06 UTC, BenjaminTan99 commented on docs/DeveloperGuide.md
> +| `*`      | user with many persons in the address book | sort persons by name           | locate a person easily                                                 |
```suggestion
| `*`      | user with many applicants in the address book | sort applicants by name           | locate an applicant easily                                                 |
```

2021-09-30 09:06 UTC, BenjaminTan99 commented on docs/DeveloperGuide.md
> +1. User enters the keywords to search by
```suggestion
1. User enters the keywords for MrTechRecruiter to search for.
```
All use case statements need full stops/periods at the end. Comment applied for all subsequent sentences.

2021-09-30 09:06 UTC, BenjaminTan99 commented on docs/DeveloperGuide.md
> +  Use case ends.
The line 'use case ends' needs to be same indentation as the start of the sentence.
```suggestion
        Use case ends.
```

2021-09-30 09:06 UTC, BenjaminTan99 commented on docs/DeveloperGuide.md
> +      Use case ends.
Same situation here. Also extension 1a should come before 2a.

2021-09-30 12:02 UTC, Harry-Gao-H reviewed
Some minor things to change, otherwise LGTM

2021-09-30 12:02 UTC, Harry-Gao-H commented on docs/DeveloperGuide.md
> +6. Should work for standard screen resolutions and higher.
Maybe the `portable` here could be ambiguous.
And `standard screen resolutions` can be specified to `industry-standard Full HD 1080p resolution`?

2021-09-30 16:41 UTC, LMAOboxhack commented on docs/DeveloperGuide.md
> +1. User enters the keywords to search by
Will fix, thanks!

2021-09-30 16:41 UTC, LMAOboxhack commented on docs/DeveloperGuide.md
> +      Use case ends.
Will fix, thanks!

2021-09-30 16:41 UTC, LMAOboxhack commented on docs/DeveloperGuide.md
> +    * 1a1. AddressBook shows an error message.
Will fix, thanks!

2021-09-30 16:41 UTC, LMAOboxhack commented on docs/DeveloperGuide.md
> +6. Should work for standard screen resolutions and higher.
Will fix, thanks!

2021-10-01 04:10 UTC, BenjaminTan99 approved these changes

2021-10-01 04:38 UTC, merged