Remove average command
AY2122S1-CS2103-F10-1/tp pull request #26
Opened 2021-09-30 11:54 UTC by BenjaminTan99

Removed the average command and converted it to class attribute.

2021-09-30 12:30 UTC, Harry-Gao-H commented on docs/DeveloperGuide.md
> +4.  MrTechRecruiter deletes the person. <br>
I think double new lines can be used to start with a new line (consistent with other parts of the document)

2021-10-01 04:21 UTC, LMAOboxhack requested changes
Some minor changes to wording, otherwise LGTM!

2021-10-01 04:21 UTC, LMAOboxhack commented on docs/DeveloperGuide.md
> +4.  MrTechRecruiter deletes the person.
```suggestion
3.  User requests to delete a specific applicant in the list using the exact name.
4.  MrTechRecruiter deletes the applicant.
```

2021-10-01 04:21 UTC, LMAOboxhack commented on docs/DeveloperGuide.md
>  1. User requests to see average rejection rates for all job positions.
```suggestion
1. User requests to see a list of all job positions
```

2021-10-01 04:21 UTC, LMAOboxhack commented on docs/DeveloperGuide.md
> +1. User keys in the particular job position using the 'find' function.
```suggestion
1. User searches for a particular job position using the 'find' function.
```

2021-10-01 04:21 UTC, LMAOboxhack commented on docs/UserGuide.md
> +A person can have any number of tags (including 0). <br>
```suggestion
An applicant can have any number of tags (including 0). <br>
```

2021-10-01 04:55 UTC, LMAOboxhack approved these changes
LGTM!

2021-10-01 04:55 UTC, merged